### ISSUE TITLE
Make data importers for Historische Geocoder datasets

### ISSUE THREAD

**Issue by bertspaan** [erfgoed-en-locatie/histograph#3]
Moved from erfgoed-en-locatie/historische-geocoder#23.
- [x] erfgoed-en-locatie/historische-geocoder#13: BAG
- [x] erfgoed-en-locatie/historische-geocoder#14: TGN
- [x] erfgoed-en-locatie/historische-geocoder#15: Gemeentegeschiedenis
- [x] erfgoed-en-locatie/historische-geocoder#16: Verdwenen dorpen
- [x] erfgoed-en-locatie/historische-geocoder#17: VOC Opvarenden
- [x] erfgoed-en-locatie/historische-geocoder#18: Illustre Lieve Vrouwe Broederschap
- [x] erfgoed-en-locatie/historische-geocoder#19: Militieregisters
- [x] erfgoed-en-locatie/historische-geocoder#20: Simon Hart-lijsten
- [x] erfgoed-en-locatie/historische-geocoder#26: Geonames
- [ ] erfgoed-en-locatie/historische-geocoder#28: Provincies, gewesten, graafschappen en bisdommen
